name: harambee_mobile_app
description: "Custom mobile application for Harambee to our church."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.10.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  shared_preferences: ^2.5.4
  provider: ^6.1.5+1
  path_provider: ^2.1.5
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
